### ISSUE TITLE
cms command

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-123#2]
please use cms sys generate command for the directory structure

**Comment by mallik3006** [comment]
Hello Professor,

I used cms to generate a command azurestorage, but i got following messages

`cms> sys command generate azurestorage
{'Command': 'Azurestorage',
 'command': 'azurestorage',
 'package': 'cloudmesh.azurestorage'}
fatal: destination path 'cloudmesh.bar' already exists and is not an empty directory.
rm -rf *.zip
rm -rf *.egg-info
rm -rf *.eggs
rm -rf docs/build
rm -rf build
rm -rf dist
find . -name '__pycache__' -delete
find . -name '*.pyc' -delete
find . -name '*.pye' -delete
rm -rf .tox
rm -f *.whl`

I earlier created one command with my firstname, so was I supposed to delete cloudmesh.bar before creating this new command?
And when I see the commands using cms help, I don't find this command. However, the folder 
cloudmesh.azurestorage got created and I copied my code under cm to this folder and pushed it under my hid (sp19-516-123):

https://github.com/cloudmesh-community/sp19-516-123/tree/master/project-code

Is there something I'm missing?

**Comment by laszewsk** [comment]
which os?

**Comment by mallik3006** [comment]
Linux (Ubuntu 18.04)

**Comment by laszewsk** [comment]
you need to remove cloudmesh.bar  or execute the command in an empty dir

**Comment by laszewsk** [comment]
once you move the cloudmesh.azurestorage to the location where you want it, go to the dir and say in it 

pip install -e .

it will than install it

**Comment by mallik3006** [comment]
I followed the instructions and generated the command again and could see the command azurestorage in the list. But I guess i made some unwanted file copies and the command was giving me issues and I accidentally deleted the folder cloudmesh.azurestorage and then I got the below errors followed by other messages whenever i invoked cms, though cms works after displaying the error messages :

`Error processing line 1 of /home/mallik30/.pyenv/versions/3.7.2/envs/ENV3/lib/python3.7/site-packages/cloudmesh.azurestorage-nspkg.pth:`

So I removed that above file and it seems to be working fine now. But I wanted to know if there to a way to restore, i mean can a command generated be properly uninstalled and regenerated?

**Comment by laszewsk** [comment]
regular pi does what you ask for

pip uninstall cloudmesh.azurestorage
pip install cloudmesh.azurestorage

if you break it by removing things elsewhere this will not work, and you may have to use a new pyenv or venv in python3. This si precisely the reason why we never want o use the native python so if we do something wrong we can recreate the python env.

**Comment by laszewsk** [comment]
i consider this solved so you can close this

**Comment by mallik3006** [comment]
Closing this issue as per comments above.
